import { User } from "./auth";
import { ApiResponse, EnhancedPagedResult } from "./api";

// Daily Reports Types
export interface DailyReportDto {
  dailyReportId: string;
  projectId: string;
  projectName: string | null;
  reportDate: string;
  status: string | null;
  reporterId: string;
  reporterName: string | null;
  submittedBy: User;
  submittedAt: string | null;
  approvedAt: string | null;
  rejectionReason: string | null;
  generalNotes: string | null;
  weatherCondition: string | null;
  temperatureHigh: number | null;
  temperatureLow: number | null;
  temperature: number | null;
  humidity: number | null;
  windSpeed: number | null;
  summary: string | null;
  workAccomplished: string | null;
  workPlanned: string | null;
  issues: string | null;
  totalWorkHours: number;
  personnelOnSite: number;
  safetyIncidents: string | null;
  qualityIssues: string | null;
  createdAt: string;
  updatedAt: string | null;
  workProgressItems: WorkProgressItemDto[] | null;
  personnelLogs: PersonnelLogDto[] | null;
  materialUsages: MaterialUsageDto[] | null;
  materialUsage: MaterialUsageDto[] | null;
  equipmentLogs: EquipmentLogDto[] | null;
  images: ImageMetadataDto[] | null;
  imageCount: number;
  links: LinkDto[] | null;
}

export interface EnhancedDailyReportDto extends DailyReportDto {
  projectLocation: string | null;
  projectManagerName: string | null;
  clientName: string | null;
  weatherDescription: string | null;
  uvIndex: number | null;
  weatherImpact: string | null;
  overallProgressPercentage: number;
  dailyProgressContribution: number;
  plannedVsActualHoursVariance: number;
  safetyScore: number;
  qualityScore: number;
  hasCriticalIssues: boolean;
  requiresManagerAttention: boolean;
  teamMembers: PersonnelSummaryDto[] | null;
  equipmentUsed: EquipmentSummaryDto[] | null;
  materialsConsumed: MaterialConsumptionDto[] | null;
  taskProgressSummary: TaskProgressSummaryDto[] | null;
  approvalStatus: string | null;
  approvedBy: User;
  approvalDate: string | null;
  approvalHistory: ApprovalHistoryDto[] | null;
  attachments: ReportAttachmentDto[] | null;
  photoCount: number;
  documentCount: number;
  autoGeneratedInsights: string[] | null;
  recommendedActions: string[] | null;
}

export interface CreateDailyReportRequest {
  projectId: string;
  reportDate: string;
  generalNotes?: string | null;
  weatherCondition?:
    | "Sunny"
    | "PartlyCloudy"
    | "Cloudy"
    | "Rainy"
    | "Stormy"
    | "Foggy"
    | "Snow"
    | "Windy"
    | null;
  temperature?: number | null;
  temperatureHigh?: number | null;
  temperatureLow?: number | null;
  humidity?: number | null;
  windSpeed?: number | null;
  workSummary: string;
  workAccomplished?: string | null;
  workPlannedNextDay?: string | null;
  issuesEncountered?: string | null;
  totalWorkHours: number;
  personnelOnSite: number;
  safetyScore: number;
  qualityScore: number;
  safetyIncidents?: string | null;
  qualityIssues?: string | null;
  dailyProgressContribution: number;
  additionalNotes?: string | null;
  workProgressItems?: CreateWorkProgressItemRequest[] | null;
  personnelLogs?: CreatePersonnelLogRequest[] | null;
  materialUsages?: CreateMaterialUsageRequest[] | null;
  equipmentLogs?: CreateEquipmentLogRequest[] | null;
}

export interface EnhancedCreateDailyReportRequest
  extends CreateDailyReportRequest {
  // Enhanced fields for advanced reporting
  enhancedMetadata?: Record<string, unknown>;
}

export interface UpdateDailyReportRequest {
  generalNotes?: string | null;
  weatherCondition?:
    | "Sunny"
    | "PartlyCloudy"
    | "Cloudy"
    | "Rainy"
    | "Stormy"
    | "Foggy"
    | "Snow"
    | "Windy"
    | null;
  temperature?: number | null;
  temperatureHigh?: number | null;
  temperatureLow?: number | null;
  humidity?: number | null;
  windSpeed?: number | null;
  workSummary?: string | null;
  workAccomplished?: string | null;
  workPlannedNextDay?: string | null;
  issuesEncountered?: string | null;
  totalWorkHours?: number | null;
  personnelOnSite?: number | null;
  safetyScore?: number | null;
  qualityScore?: number | null;
  safetyIncidents?: string | null;
  qualityIssues?: string | null;
  dailyProgressContribution?: number | null;
  additionalNotes?: string | null;
}

// Work Progress Items
export interface WorkProgressItemDto {
  workProgressItemId: string;
  reportId: string;
  taskId: string | null;
  taskTitle: string | null;
  activity: string | null;
  description: string | null;
  hoursWorked: number;
  percentageComplete: number;
  workersAssigned: number;
  notes: string | null;
  issues: string | null;
  nextSteps: string | null;
  createdAt: string;
}

export interface CreateWorkProgressItemRequest {
  reportId: string;
  taskId?: string | null;
  activity: string;
  description?: string | null;
  hoursWorked: number;
  percentageComplete: number;
  workersAssigned: number;
  notes?: string | null;
  issues?: string | null;
  nextSteps?: string | null;
}

export interface UpdateWorkProgressItemRequest {
  activity?: string | null;
  description?: string | null;
  hoursWorked?: number | null;
  percentageComplete?: number | null;
  workersAssigned?: number | null;
  notes?: string | null;
  issues?: string | null;
  nextSteps?: string | null;
}

// Personnel Logs
export interface PersonnelLogDto {
  personnelLogId: string;
  reportId: string;
  name: string | null;
  role: string | null;
  hoursWorked: number;
  tasks: string | null;
  specialNotes: string | null;
  createdAt: string;
}

export interface CreatePersonnelLogRequest {
  reportId: string;
  name: string;
  role: string;
  hoursWorked: number;
  tasks?: string | null;
  specialNotes?: string | null;
}

// Material Usage
export interface MaterialUsageDto {
  materialUsageId: string;
  reportId: string;
  materialName: string | null;
  quantityUsed: number;
  unit: string | null;
  cost: number | null;
  supplier: string | null;
  notes: string | null;
  createdAt: string;
}

export interface CreateMaterialUsageRequest {
  materialId: string;
  quantity: number;
  unit: string;
  unitCost?: number | null;
  notes?: string | null;
}

// Equipment Logs
export interface EquipmentLogDto {
  equipmentLogId: string;
  reportId: string;
  equipmentName: string | null;
  type: string | null;
  hoursUsed: number;
  condition: string | null;
  issues: string | null;
}

export interface CreateEquipmentLogRequest {
  reportId: string;
  equipmentName: string;
  type: string;
  hoursUsed: number;
  condition: string;
  issues?: string | null;
  maintenanceNotes?: string | null;
}

// Support Types
export interface PersonnelSummaryDto {
  userId: string;
  name: string | null;
  role: string | null;
  hoursWorked: number;
  specialAssignments: string | null;
}

export interface EquipmentSummaryDto {
  equipmentId: string;
  name: string | null;
  type: string | null;
  hoursUsed: number;
  condition: string | null;
  issues: string | null;
}

export interface MaterialConsumptionDto {
  materialId: string;
  materialName: string | null;
  quantityUsed: number;
  unit: string | null;
  cost: number | null;
  supplier: string | null;
  notes: string | null;
}

export interface TaskProgressSummaryDto {
  taskId: string;
  taskName: string | null;
  startPercentage: number;
  endPercentage: number;
  progressMade: number;
  status: string | null;
  isOnSchedule: boolean;
}

export interface ApprovalHistoryDto {
  id: string;
  action: string | null;
  actorId: string;
  actorName: string | null;
  timestamp: string;
  comments: string | null;
}

export interface ReportAttachmentDto {
  attachmentId: string;
  fileName: string | null;
  fileSize: number;
  contentType: string | null;
  uploadedAt: string;
  uploadedBy: string | null;
}

export interface ImageMetadataDto {
  imageId: string;
  projectId: string;
  taskId: string | null;
  fileName: string | null;
  contentType: string | null;
  fileSize: number;
  uploadedAt: string;
  uploadedBy: string | null;
  captureTimestamp: string | null;
  gpsLatitude: number | null;
  gpsLongitude: number | null;
  deviceModel: string | null;
  description: string | null;
}

export interface LinkDto {
  rel: string | null;
  href: string | null;
  method: string | null;
}

// Daily Report Analytics
export interface DailyReportAnalyticsDto {
  projectId: string;
  projectName: string | null;
  analysisPeriodStart: string;
  analysisPeriodEnd: string;
  totalReports: number;
  totalHoursLogged: number;
  averageHoursPerDay: number;
  averageSafetyScore: number;
  averageQualityScore: number;
  totalProgressContribution: number;
  averageProgressPerDay: number;
  daysAheadBehindSchedule: number;
  totalCriticalIssues: number;
  weatherDelayDays: number;
  topIssueCategories: string[] | null;
  averageTeamSize: number;
  productivityIndex: number;
  topPerformers: PersonnelPerformanceDto[] | null;
  weatherConditionDays: { [key: string]: number } | null;
  weatherImpactScore: number;
}

export interface PersonnelPerformanceDto {
  userId: string;
  name: string | null;
  totalHours: number;
  averageHoursPerDay: number;
  averageSafetyScore: number;
  averageQualityScore: number;
  productivityScore: number;
}

// Daily Report Validation
export interface DailyReportValidationResultDto {
  isValid: boolean;
  warnings: ValidationWarningDto[] | null;
  suggestions: string[] | null;
  autoCorrections: ValidationCorrectionDto[] | null;
}

export interface ValidationWarningDto {
  field: string | null;
  message: string | null;
  severity: string | null;
  suggestion: string | null;
}

export interface ValidationCorrectionDto {
  field: string | null;
  originalValue: string | null;
  suggestedValue: string | null;
  reason: string | null;
}

// Daily Report Templates
export interface DailyReportTemplateDto {
  templateId: string;
  name: string | null;
  description: string | null;
  projectId: string;
  projectType: string | null;
  fields: TemplateFieldDto[] | null;
  requiredFields: string[] | null;
  defaultValues: { [key: string]: any } | null;
  validationRules: TemplateValidationRuleDto[] | null;
  isDefault: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string | null;
}

export interface TemplateFieldDto {
  name: string | null;
  label: string | null;
  type: string | null;
  required: boolean;
  options: string[] | null;
  defaultValue: string | null;
  validation: string | null;
}

export interface TemplateValidationRuleDto {
  field: string | null;
  rule: string | null;
  message: string | null;
  parameters: { [key: string]: any } | null;
}

// Daily Report Insights
export interface DailyReportInsightsDto {
  projectId: string;
  projectName: string | null;
  generatedAt: string;
  performanceInsights: string[] | null;
  productivityRecommendations: string[] | null;
  riskLevel: string | null;
  riskFactors: string[] | null;
  scheduleOptimizations: string[] | null;
  weatherImpactInsights: string[] | null;
  weatherPreparationTips: string[] | null;
  trends: TrendInsightDto[] | null;
}

export interface TrendInsightDto {
  metric: string | null;
  trend: string | null;
  period: string | null;
  significance: string | null;
  recommendation: string | null;
}

// Bulk Operations
export interface DailyReportBulkApprovalRequest {
  reportIds: string[];
  comments?: string | null;
  approvalLevel?: string | null;
}

export interface BulkOperationResultDto {
  totalRequested: number;
  successful: number;
  failed: number;
  errors: BulkOperationErrorDto[] | null;
  results: BulkOperationItemResultDto[] | null;
}

export interface BulkOperationErrorDto {
  itemId: string | null;
  error: string | null;
  details: string | null;
}

export interface BulkOperationItemResultDto {
  itemId: string | null;
  success: boolean;
  message: string | null;
}

// Export/Import
export interface DailyReportExportRequest {
  projectId: string;
  startDate?: string | null;
  endDate?: string | null;
  format?: "csv" | "excel" | "pdf" | "json" | null;
  includeImages?: boolean;
  includeDocuments?: boolean;
  includeAttachments?: boolean;
  includeAnalytics?: boolean;
  fieldsToInclude?: string[] | null;
}

// Weekly Summary
export interface WeeklySummaryDto {
  weekStartDate: string;
  weekEndDate: string;
  totalReports: number;
  completedTasks: number;
  pendingTasks: number;
  totalHoursWorked: number;
  averageProgress: number;
  topIssues: string[] | null;
  completedMilestones: string[] | null;
  reports: DailyReportDto[] | null;
}

// API Response Types
export type DailyReportDtoApiResponse = ApiResponse<DailyReportDto>;
export type DailyReportDtoEnhancedPagedResultApiResponse = ApiResponse<
  EnhancedPagedResult<EnhancedDailyReportDto>
>;
export type DailyReportAnalyticsDtoApiResponse =
  ApiResponse<DailyReportAnalyticsDto>;
export type DailyReportInsightsDtoApiResponse =
  ApiResponse<DailyReportInsightsDto>;
export type DailyReportValidationResultDtoApiResponse =
  ApiResponse<DailyReportValidationResultDto>;
export type DailyReportTemplateDtoListApiResponse = ApiResponse<
  DailyReportTemplateDto[]
>;
export type WorkProgressItemDtoApiResponse = ApiResponse<WorkProgressItemDto>;
export type WeeklySummaryDtoApiResponse = ApiResponse<WeeklySummaryDto>;
export type BulkOperationResultDtoApiResponse =
  ApiResponse<BulkOperationResultDto>;
export type ApprovalHistoryDtoListApiResponse = ApiResponse<
  ApprovalHistoryDto[]
>;
